//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//


package ru.ics.engineerService.ws_schemas.ec2model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvailabilityZoneItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailabilityZoneItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zoneName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zoneState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="messageSet" type="{http://ec2.amazonaws.com/doc/2010-11-15/}AvailabilityZoneMessageSetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailabilityZoneItemType", propOrder = {
    "zoneName",
    "zoneState",
    "regionName",
    "messageSet"
})
public class AvailabilityZoneItemType {

    @XmlElement(required = true)
    protected String zoneName;
    @XmlElement(required = true)
    protected String zoneState;
    @XmlElement(required = true)
    protected String regionName;
    @XmlElement(required = true)
    protected AvailabilityZoneMessageSetType messageSet;

    /**
     * Gets the value of the zoneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneName() {
        return zoneName;
    }

    /**
     * Sets the value of the zoneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneName(String value) {
        this.zoneName = value;
    }

    /**
     * Gets the value of the zoneState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneState() {
        return zoneState;
    }

    /**
     * Sets the value of the zoneState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneState(String value) {
        this.zoneState = value;
    }

    /**
     * Gets the value of the regionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * Sets the value of the regionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionName(String value) {
        this.regionName = value;
    }

    /**
     * Gets the value of the messageSet property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityZoneMessageSetType }
     *     
     */
    public AvailabilityZoneMessageSetType getMessageSet() {
        return messageSet;
    }

    /**
     * Sets the value of the messageSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityZoneMessageSetType }
     *     
     */
    public void setMessageSet(AvailabilityZoneMessageSetType value) {
        this.messageSet = value;
    }

}
