//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//


package ru.ics.engineerService.ws_schemas.ec2model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConversionTaskType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConversionTaskType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conversionTaskId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expirationTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="importVolume" type="{http://ec2.amazonaws.com/doc/2010-11-15/}ImportVolumeTaskDetailsType" minOccurs="0"/>
 *           &lt;element name="importInstance" type="{http://ec2.amazonaws.com/doc/2010-11-15/}ImportInstanceTaskDetailsType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConversionTaskType", propOrder = {
    "conversionTaskId",
    "expirationTime",
    "importVolume",
    "importInstance",
    "state",
    "statusMessage"
})
public class ConversionTaskType {

    @XmlElement(required = true)
    protected String conversionTaskId;
    protected String expirationTime;
    protected ImportVolumeTaskDetailsType importVolume;
    protected ImportInstanceTaskDetailsType importInstance;
    @XmlElement(required = true)
    protected String state;
    protected String statusMessage;

    /**
     * Gets the value of the conversionTaskId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversionTaskId() {
        return conversionTaskId;
    }

    /**
     * Sets the value of the conversionTaskId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversionTaskId(String value) {
        this.conversionTaskId = value;
    }

    /**
     * Gets the value of the expirationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationTime() {
        return expirationTime;
    }

    /**
     * Sets the value of the expirationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationTime(String value) {
        this.expirationTime = value;
    }

    /**
     * Gets the value of the importVolume property.
     * 
     * @return
     *     possible object is
     *     {@link ImportVolumeTaskDetailsType }
     *     
     */
    public ImportVolumeTaskDetailsType getImportVolume() {
        return importVolume;
    }

    /**
     * Sets the value of the importVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportVolumeTaskDetailsType }
     *     
     */
    public void setImportVolume(ImportVolumeTaskDetailsType value) {
        this.importVolume = value;
    }

    /**
     * Gets the value of the importInstance property.
     * 
     * @return
     *     possible object is
     *     {@link ImportInstanceTaskDetailsType }
     *     
     */
    public ImportInstanceTaskDetailsType getImportInstance() {
        return importInstance;
    }

    /**
     * Sets the value of the importInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportInstanceTaskDetailsType }
     *     
     */
    public void setImportInstance(ImportInstanceTaskDetailsType value) {
        this.importInstance = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

}
