//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//


package ru.ics.engineerService.ws_schemas.ec2model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescribeConversionTasksResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeConversionTasksResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conversionTasks" type="{http://ec2.amazonaws.com/doc/2010-11-15/}ConversionTaskSetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeConversionTasksResponseType", propOrder = {
    "conversionTasks"
})
public class DescribeConversionTasksResponseType {

    @XmlElement(required = true)
    protected ConversionTaskSetType conversionTasks;

    /**
     * Gets the value of the conversionTasks property.
     * 
     * @return
     *     possible object is
     *     {@link ConversionTaskSetType }
     *     
     */
    public ConversionTaskSetType getConversionTasks() {
        return conversionTasks;
    }

    /**
     * Sets the value of the conversionTasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConversionTaskSetType }
     *     
     */
    public void setConversionTasks(ConversionTaskSetType value) {
        this.conversionTasks = value;
    }

}
