//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//


package ru.ics.engineerService.ws_schemas.ec2model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiskImageDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiskImageDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bytes" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="importManifestUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiskImageDetailType", propOrder = {
    "format",
    "bytes",
    "importManifestUrl"
})
public class DiskImageDetailType {

    @XmlElement(required = true)
    protected String format;
    protected long bytes;
    @XmlElement(required = true)
    protected String importManifestUrl;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the bytes property.
     * 
     */
    public long getBytes() {
        return bytes;
    }

    /**
     * Sets the value of the bytes property.
     * 
     */
    public void setBytes(long value) {
        this.bytes = value;
    }

    /**
     * Gets the value of the importManifestUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportManifestUrl() {
        return importManifestUrl;
    }

    /**
     * Sets the value of the importManifestUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportManifestUrl(String value) {
        this.importManifestUrl = value;
    }

}
