//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//


package ru.ics.engineerService.ws_schemas.ec2model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImportInstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportInstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="launchSpecification" type="{http://ec2.amazonaws.com/doc/2010-11-15/}ImportInstanceLaunchSpecificationType"/>
 *         &lt;element name="diskImageSet" type="{http://ec2.amazonaws.com/doc/2010-11-15/}DiskImageSetType"/>
 *         &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportInstanceType", propOrder = {
    "description",
    "launchSpecification",
    "diskImageSet",
    "platform"
})
public class ImportInstanceType {

    protected String description;
    @XmlElement(required = true)
    protected ImportInstanceLaunchSpecificationType launchSpecification;
    @XmlElement(required = true)
    protected DiskImageSetType diskImageSet;
    @XmlElement(required = true)
    protected String platform;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the launchSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link ImportInstanceLaunchSpecificationType }
     *     
     */
    public ImportInstanceLaunchSpecificationType getLaunchSpecification() {
        return launchSpecification;
    }

    /**
     * Sets the value of the launchSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportInstanceLaunchSpecificationType }
     *     
     */
    public void setLaunchSpecification(ImportInstanceLaunchSpecificationType value) {
        this.launchSpecification = value;
    }

    /**
     * Gets the value of the diskImageSet property.
     * 
     * @return
     *     possible object is
     *     {@link DiskImageSetType }
     *     
     */
    public DiskImageSetType getDiskImageSet() {
        return diskImageSet;
    }

    /**
     * Sets the value of the diskImageSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiskImageSetType }
     *     
     */
    public void setDiskImageSet(DiskImageSetType value) {
        this.diskImageSet = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

}
