//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ec2.amazonaws.com/doc/2010-11-15/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.ics.engineerService.ws_schemas.ec2model;
