//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//


package ru.spbstu.ics.cloudclient.ec2model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescribeReservedInstancesOfferingsResponseSetItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeReservedInstancesOfferingsResponseSetItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reservedInstancesOfferingId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="instanceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="availabilityZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="fixedPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="usagePrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="productDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeReservedInstancesOfferingsResponseSetItemType", propOrder = {
    "reservedInstancesOfferingId",
    "instanceType",
    "availabilityZone",
    "duration",
    "fixedPrice",
    "usagePrice",
    "productDescription"
})
public class DescribeReservedInstancesOfferingsResponseSetItemType {

    @XmlElement(required = true)
    protected String reservedInstancesOfferingId;
    @XmlElement(required = true)
    protected String instanceType;
    @XmlElement(required = true)
    protected String availabilityZone;
    protected long duration;
    protected double fixedPrice;
    protected double usagePrice;
    @XmlElement(required = true)
    protected String productDescription;

    /**
     * Gets the value of the reservedInstancesOfferingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservedInstancesOfferingId() {
        return reservedInstancesOfferingId;
    }

    /**
     * Sets the value of the reservedInstancesOfferingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservedInstancesOfferingId(String value) {
        this.reservedInstancesOfferingId = value;
    }

    /**
     * Gets the value of the instanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceType() {
        return instanceType;
    }

    /**
     * Sets the value of the instanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceType(String value) {
        this.instanceType = value;
    }

    /**
     * Gets the value of the availabilityZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityZone() {
        return availabilityZone;
    }

    /**
     * Sets the value of the availabilityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityZone(String value) {
        this.availabilityZone = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public long getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(long value) {
        this.duration = value;
    }

    /**
     * Gets the value of the fixedPrice property.
     * 
     */
    public double getFixedPrice() {
        return fixedPrice;
    }

    /**
     * Sets the value of the fixedPrice property.
     * 
     */
    public void setFixedPrice(double value) {
        this.fixedPrice = value;
    }

    /**
     * Gets the value of the usagePrice property.
     * 
     */
    public double getUsagePrice() {
        return usagePrice;
    }

    /**
     * Sets the value of the usagePrice property.
     * 
     */
    public void setUsagePrice(double value) {
        this.usagePrice = value;
    }

    /**
     * Gets the value of the productDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * Sets the value of the productDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDescription(String value) {
        this.productDescription = value;
    }

}
