//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//


package ru.spbstu.ics.cloudclient.ec2model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescribeImagesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeImagesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="executableBySet" type="{http://ec2.amazonaws.com/doc/2010-11-15/}DescribeImagesExecutableBySetType" minOccurs="0"/>
 *         &lt;element name="imagesSet" type="{http://ec2.amazonaws.com/doc/2010-11-15/}DescribeImagesInfoType"/>
 *         &lt;element name="ownersSet" type="{http://ec2.amazonaws.com/doc/2010-11-15/}DescribeImagesOwnersType" minOccurs="0"/>
 *         &lt;element name="filterSet" type="{http://ec2.amazonaws.com/doc/2010-11-15/}FilterSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeImagesType", propOrder = {
    "executableBySet",
    "imagesSet",
    "ownersSet",
    "filterSet"
})
public class DescribeImagesType {

    protected DescribeImagesExecutableBySetType executableBySet;
    @XmlElement(required = true)
    protected DescribeImagesInfoType imagesSet;
    protected DescribeImagesOwnersType ownersSet;
    protected FilterSetType filterSet;

    /**
     * Gets the value of the executableBySet property.
     * 
     * @return
     *     possible object is
     *     {@link DescribeImagesExecutableBySetType }
     *     
     */
    public DescribeImagesExecutableBySetType getExecutableBySet() {
        return executableBySet;
    }

    /**
     * Sets the value of the executableBySet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescribeImagesExecutableBySetType }
     *     
     */
    public void setExecutableBySet(DescribeImagesExecutableBySetType value) {
        this.executableBySet = value;
    }

    /**
     * Gets the value of the imagesSet property.
     * 
     * @return
     *     possible object is
     *     {@link DescribeImagesInfoType }
     *     
     */
    public DescribeImagesInfoType getImagesSet() {
        return imagesSet;
    }

    /**
     * Sets the value of the imagesSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescribeImagesInfoType }
     *     
     */
    public void setImagesSet(DescribeImagesInfoType value) {
        this.imagesSet = value;
    }

    /**
     * Gets the value of the ownersSet property.
     * 
     * @return
     *     possible object is
     *     {@link DescribeImagesOwnersType }
     *     
     */
    public DescribeImagesOwnersType getOwnersSet() {
        return ownersSet;
    }

    /**
     * Sets the value of the ownersSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescribeImagesOwnersType }
     *     
     */
    public void setOwnersSet(DescribeImagesOwnersType value) {
        this.ownersSet = value;
    }

    /**
     * Gets the value of the filterSet property.
     * 
     * @return
     *     possible object is
     *     {@link FilterSetType }
     *     
     */
    public FilterSetType getFilterSet() {
        return filterSet;
    }

    /**
     * Sets the value of the filterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterSetType }
     *     
     */
    public void setFilterSet(FilterSetType value) {
        this.filterSet = value;
    }

}
