//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.29 at 10:35:36 PM MSK 
//


package ru.spbstu.ics.cloudclient.ec2model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstanceBlockDeviceMappingItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstanceBlockDeviceMappingItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="virtualName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="ebs" type="{http://ec2.amazonaws.com/doc/2010-11-15/}InstanceEbsBlockDeviceType"/>
 *           &lt;element name="noDevice" type="{http://ec2.amazonaws.com/doc/2010-11-15/}EmptyElementType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstanceBlockDeviceMappingItemType", propOrder = {
    "deviceName",
    "virtualName",
    "ebs",
    "noDevice"
})
public class InstanceBlockDeviceMappingItemType {

    @XmlElement(required = true)
    protected String deviceName;
    protected String virtualName;
    protected InstanceEbsBlockDeviceType ebs;
    protected EmptyElementType noDevice;

    /**
     * Gets the value of the deviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * Sets the value of the deviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceName(String value) {
        this.deviceName = value;
    }

    /**
     * Gets the value of the virtualName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirtualName() {
        return virtualName;
    }

    /**
     * Sets the value of the virtualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirtualName(String value) {
        this.virtualName = value;
    }

    /**
     * Gets the value of the ebs property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceEbsBlockDeviceType }
     *     
     */
    public InstanceEbsBlockDeviceType getEbs() {
        return ebs;
    }

    /**
     * Sets the value of the ebs property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceEbsBlockDeviceType }
     *     
     */
    public void setEbs(InstanceEbsBlockDeviceType value) {
        this.ebs = value;
    }

    /**
     * Gets the value of the noDevice property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyElementType }
     *     
     */
    public EmptyElementType getNoDevice() {
        return noDevice;
    }

    /**
     * Sets the value of the noDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyElementType }
     *     
     */
    public void setNoDevice(EmptyElementType value) {
        this.noDevice = value;
    }

}
